### ISSUE TITLE
Retrieving data from tsconfig.json

### ISSUE THREAD

**Issue by enstain** [marzelin/convert-tsconfig-paths-to-webpack-aliases#1]
Hi, marzelin! Great package you did, thanks for that) But there is a one problem I stucked with.

As I see in your source code, you try to read properties "baseUrl" and "paths" directly from the root of tsconfig json object. But the point is that these two properties are placed inside `compilerOptions` field. At least it is required by my typescript 2.3.4 version. If I put these properties twice, inside root and inside compilerOptions then it's not recognized by ts compiler. So, only one way is to change the mapping data from tsconfig

So, do you have some special reason to retrieve the data from tsconfig root or this is ok to change this?

**Comment by enstain** [comment]
Other working solution is to define aliases constant like this: 

```
const aliases = convertPathsToAliases(tsconfig.compilerOptions);
```

You might mention it in readme)

**Comment by marzelin** [comment]
Indeed, it should look for paths in `compilerOptions`. Thanks for pointing this out :+1: 
I'll fix this in the next version.
