### ISSUE TITLE
Just a note of gratefulness! Webstorm got so much better with this.

### ISSUE THREAD

**Issue by D1no** [marzelin/convert-tsconfig-paths-to-webpack-aliases#3]
I just want to thank you for this package. We use typescript and aliases to organize our code. With the new WebStorm 2017.2 EAP build (https://blog.jetbrains.com/webstorm/2017/06/webstorm-2017-2-eap-172-2827/), WebStorm is now able to parse webpack configs.

So we just dropped your package as a dev dependency with your example code and webstorm recognises now all alias paths in all files, not just typescript files!

Thank you for this!
Dino

**Comment by marzelin** [comment]
Awesome. Love this type of issues :). Thanks for your kind words.
